#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aideapp-deployment
  namespace: default
  labels:
    app: aide-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aide-app
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: aide-app
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: aideapp-container
        image: khingarthur/aide-app:9
        ports:
        - containerPort: 3000
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: aide-service
  labels:
    app: aide-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: aide-app
